"""empty message

Revision ID: 50d4865c6ce0
Revises: 186387f3dbc3
Create Date: 2024-03-29 15:57:43.088341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d4865c6ce0'
down_revision = '186387f3dbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('active')

    # ### end Alembic commands ###
