"""empty message

Revision ID: acff34d294ae
Revises: 34a2acb90d37
Create Date: 2024-05-18 15:13:13.025737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acff34d294ae'
down_revision = '34a2acb90d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_month', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_year', sa.Float(), nullable=False))
        batch_op.drop_column('duration_days')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), nullable=False))
        batch_op.drop_column('price_year')
        batch_op.drop_column('price_month')

    # ### end Alembic commands ###
