"""empty message

Revision ID: c12af5a298ae
Revises: acff34d294ae
Create Date: 2024-05-24 16:42:22.882724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12af5a298ae'
down_revision = 'acff34d294ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_search_supreme_court', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_search_laws', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_search_constitution', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_search_conseil', sa.Boolean(), nullable=True))
        batch_op.drop_column('searches_per_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searches_per_day', sa.INTEGER(), nullable=False))
        batch_op.drop_column('has_search_conseil')
        batch_op.drop_column('has_search_constitution')
        batch_op.drop_column('has_search_laws')
        batch_op.drop_column('has_search_supreme_court')

    # ### end Alembic commands ###
