"""empty message

Revision ID: c665a7793dcb
Revises: 32f979c3e900
Create Date: 2024-04-05 10:24:44.382051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c665a7793dcb'
down_revision = '32f979c3e900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_your_model_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_constraint('uq_your_model_name', type_='unique')

    # ### end Alembic commands ###
